version: 2.1

jobs:
  build-and-test:  
    machine: 
      image: ubuntu-2004:current 
      docker_layer_caching: true
        
    steps: 
      - checkout 
      - run: 
          name: Install dependencies
          command: make deps 
      - run: 
          name: Run Linter
          command: make lint
      - run: 
          name: Run Tests
          command: make test       
      - run:
          name: Build Docker Image
          command: make docker_build
      - run:
          name: Push Docker Image to Docker Hub
          command: make docker_push

workflows: 
  basic:  
    jobs: 
      - build-and-test
